module.exports = {
    UserRepository: require('./user-repository'),
    SessionRepository: require('./session-repository'),
    FlightRepository: require('./flight-repository'),
    FlightScheduleRepository: require('./flightschedule-repository'),
    AirportRepository: require('./airport-repository'),
    AirlineRepository: require('./airline-repository'),
    AirplaneRepository: require('./airplane-repository'),
    FlightScheduleFareRepository: require('./flightschedulefare-repository'),
    SeatRepository: require('./seat-repository'),
    PassengerRepository: require('./passenger-repository'),
    BookingRepository: require('./booking-repository'),
    TicketRepository: require('./ticket-repository'),
    BookingServiceRepository: require('./bookingservice-repository'),
    ExtraServiceRepository: require('./extraservice-repository'),
}